POST http://localhost:3333/courses
Content-Type: application/json

{
  "title": "Curso de React"
}

###

GET http://localhost:3333/courses


###

GET http://localhost:3333/courses/56a434ee-72a5-4485-b17c-493d56a006cb
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0ODkwZTE3ZS03YTIwLTRkNTMtOGFjZS01ZjMwNDcwMjk0M2EiLCJyb2xlIjoic3R1ZGVudCIsImlhdCI6MTc1NzM1NDYwN30.4jNwTVmnfFY7fjdagMVjJ5pwEUvjEYg8PZ1R_V9HTIo

###

POST http://localhost:3333/sessions
Content-Type: application/json

{
  "email": "Pedro60@gmail.com",
  "password": "123456"
}