POST http://localhost:3333/courses
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0ODkwZTE3ZS03YTIwLTRkNTMtOGFjZS01ZjMwNDcwMjk0M2EiLCJyb2xlIjoibWFuYWdlciIsImlhdCI6MTc1NzM2MDc5MH0.nQXjPvioRrJ1DBqClEqLZBdSQtVnOuoSlW-eBsJT2JE

{
  "title": "Curso de Node"
}

###

GET http://localhost:3333/courses


###

GET http://localhost:3333/courses/56a434ee-72a5-4485-b17c-493d56a006cb
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0ODkwZTE3ZS03YTIwLTRkNTMtOGFjZS01ZjMwNDcwMjk0M2EiLCJyb2xlIjoibWFuYWdlciIsImlhdCI6MTc1NzM2MDc5MH0.nQXjPvioRrJ1DBqClEqLZBdSQtVnOuoSlW-eBsJT2JE

###

POST http://localhost:3333/sessions
Content-Type: application/json

{
  "email": "Pedro60@gmail.com",
  "password": "123456"
}